from sqlalchemy import text
from sqlalchemy.orm import Session
from database import engine


def insert_lgu_records_if_empty():
    # First SQL: LGUs
    lgu_sql = """
        INSERT INTO lgu_records (lgu_name, lgu_classification) VALUES
        ('Alcantara', 'Municipality'),
        ('Alcoy', 'Municipality'),
        ('Alegria', 'Municipality'),
        ('Aloguinsan', 'Municipality'),
        ('Argao', 'Municipality'),
        ('Asturias', 'Municipality'),
        ('Badian', 'Municipality'),
        ('Balamban', 'Municipality'),
        ('Bantayan', 'Municipality'),
        ('Barili', 'Municipality'),
        ('City of Bogo', 'City'),
        ('Boljoon', 'Municipality'),
        ('Borbon', 'Municipality'),
        ('City of Carcar', 'City'),
        ('Carmen', 'Municipality'),
        ('Catmon', 'Municipality'),
        ('Cebu City', 'City'),
        ('Compostela', 'Municipality'),
        ('Consolacion', 'Municipality'),
        ('Cordova', 'Municipality'),
        ('Daanbantayan', 'Municipality'),
        ('Dalaguete', 'Municipality'),
        ('Danao City', 'City'),
        ('Dumanjug', 'Municipality'),
        ('Ginatilan', 'Municipality'),
        ('Lapu-lapu City', 'City'),
        ('Liloan', 'Municipality'),
        ('Madridejos', 'Municipality'),
        ('Malabuyoc', 'Municipality'),
        ('Mandaue City', 'City'),
        ('Medellin', 'Municipality'),
        ('Minglanilla', 'Municipality'),
        ('Moalboal', 'Municipality'),
        ('City of Naga', 'City'),
        ('Oslob', 'Municipality'),
        ('Pilar', 'Municipality'),
        ('Pinamungahan', 'Municipality'),
        ('Poro', 'Municipality'),
        ('Ronda', 'Municipality'),
        ('Samboan', 'Municipality'),
        ('San Fernando', 'Municipality'),
        ('San Francisco', 'Municipality'),
        ('San Remegio', 'Municipality'),
        ('Santa Fe', 'Municipality'),
        ('Santander', 'Municipality'),
        ('Sibonga', 'Municipality'),
        ('Sogod', 'Municipality'),
        ('Tabogon', 'Municipality'),
        ('Tabuelan', 'Municipality'),
        ('City of Talisay', 'City'),
        ('Toledo City', 'City'),
        ('Tuburan', 'Municipality'),
        ('Tudela', 'Municipality');
    """

    # Second SQL: Example second table
    barangay_sql = """

 INSERT INTO baranggay_records (name, lgu_id) VALUES('Cabadiangan', 1),
 ('Palanas', 1),
 ('Cabil-isan', 1),
 ('Poblacion', 1),
 ('Candabong', 1),
 ('Polo', 1),
 ('Lawaan', 1),
 ('Salagmaya', 1),
 ('Manga', 1),
 ('Atabay', 2),
 ('Pasol', 2),
 ('Daan-Lungsod', 2),
 ('Poblacion', 2),
 ('Guiwang', 2),
 ('Pugalo', 2),
 ('Nug-as', 2),
 ('San Agustin', 2),
 ('Compostela', 3),
 ('Montpeller', 3),
 ('Guadalupe', 3),
 ('Poblacion', 3),
 ('Legaspi', 3),
 ('Santa Filomena', 3),
 ('Lepanto', 3),
 ('Valencia', 3),
 ('Madridejos', 3),
 ('Angilan', 4),
 ('Punay', 4),
 ('Bojo', 4),
 ('Rosario', 4),
 ('Bonbon', 4),
 ('Saksak', 4),
 ('Esperanza', 4),
 ('Tampa-an', 4),
 ('Kandingan', 4),
 ('Toyokon', 4),
 ('Kantabogon', 4),
 ('Zaragosa', 4),
 ('Kawasan', 4),
 ('Zaragosa', 4),
 ('Olango', 4),
 ('Alambijud', 5),
 ('Lamacan', 5),
 ('Anajao', 5),
 ('Langtad', 5),
 ('Apo', 5),
 ('Langub', 5),
 ('Balaas', 5),
 ('Lapay', 5),
 ('Balisong', 5),
 ('Lengigon', 5),
 ('Binlod', 5),
 ('Linut-od', 5),
 ('Bogo', 5),
 ('Mabasa', 5),
 ('Butong', 5),
 ('Mandilikit', 5),
 ('Bug-ot', 5),
 ('Mompeller', 5),
 ('Bulasa', 5),
 ('Panadtaran', 5),
 ('Calagasan', 5),
 ('Poblacion', 5),
 ('Canbantug', 5),
 ('Sua', 5),
 ('Canbanua', 5),
 ('Sumaguan', 5),
 ('Cansuje', 5),
 ('Tabayag', 5),
 ('Capio-an', 5),
 ('Talaga', 5),
 ('Casay', 5),
 ('Talaytay', 5),
 ('Catang', 5),
 ('Talo-ot', 5),
 ('Colawin', 5),
 ('Tiguib', 5),
 ('Conalum', 5),
 ('Tulang', 5),
 ('Guiwanon', 5),
 ('Tulic', 5),
 ('Gutlang', 5),
 ('Ubaub', 5),
 ('Jampang', 5),
 ('Usmad', 5),
 ('Jomgao', 5),
 ('Agbanga', 6),
 ('New Bago', 6),
 ('Agtugop', 6),
 ('Owak', 6),
 ('Bago', 6),
 ('Poblacion', 6),
 ('Bairan', 6),
 ('Saksak', 6),
 ('Banban', 6),
 ('San Isidro', 6),
 ('Baye', 6),
 ('San Roque', 6),
 ('Bog-o', 6),
 ('Santa Lucia', 6),
 ('Kaluangan', 6),
 ('Santa Rita', 6),
 ('Lanao', 6),
 ('Tag-amakan', 6),
 ('Langub', 6),
 ('Tagbubonga', 6),
 ('Looc Norte', 6),
 ('Tubigagmanok', 6),
 ('Lunas', 6),
 ('Tubod', 6),
 ('Magcalape', 6),
 ('Ubogon', 6),
 ('Manguiao', 6),
 ('Alawijao', 7),
 ('Manduyong', 7),
 ('Balhaan', 7),
 ('Matutinao', 7),
 ('Banhigan', 7),
 ('Patong', 7),
 ('Basak', 7),
 ('Poblacion', 7),
 ('Basiao', 7),
 ('Sanlagan', 7),
 ('Bato', 7),
 ('Santicon', 7),
 ('Bugas', 7),
 ('Sohoton', 7),
 ('Calangcang', 7),
 ('Sulsugan', 7),
 ('Candiis', 7),
 ('Talayong', 7),
 ('Dagatan', 7),
 ('Taytay', 7),
 ('Dobdob', 7),
 ('Tigbao', 7),
 ('Ginablan', 7),
 ('Tiguib', 7),
 ('Lambug', 7),
 ('Tubod', 7),
 ('Malabago', 7),
 ('Zaragosa', 7),
 ('Malhiao', 7),
 ('Abucayan', 8),
 ('Ginatilan', 8),
 ('Aliwanay', 8),
 ('Hingatmonan', 8),
 ('Arpili', 8),
 ('Lamesa', 8),
 ('Bayong', 8),
 ('Liki', 8),
 ('Biasong', 8),
 ('Luca', 8),
 ('Buanoy', 8),
 ('Matun-og', 8),
 ('Cabagdalan', 8),
 ('Nangka', 8),
 ('Cabasiangan', 8),
 ('Pondol', 8),
 ('Cambuhawe', 8),
 ('Prenza', 8),
 ('Cansomoroy', 8),
 ('Singsing', 8),
 ('Cantibas', 8),
 ('Sunog', 8),
 ('Cantuod', 8),
 ('Vito', 8),
 ('Duangan', 8),
 ('Baliwagan (Pob.)', 8),
 ('Gaas', 8),
 ('Santa Cruz-Santo Niño (Pob.)', 8),
 ('Atop-atop', 9),
 ('Luyongbaybay', 9),
 ('Baigad', 9),
 ('Mojon', 9),
 ('Baod', 9),
 ('Obo-ob', 9),
 ('Binaobao (Pob.)', 9),
 ('Patao', 9),
 ('Botigues', 9),
 ('Putian', 9),
 ('Kabac', 9),
 ('Sillon', 9),
 ('Doong', 9),
 ('Sungko', 9),
 ('Hilotongan', 9),
 ('Suba (Pob.)', 9),
 ('Guiwanon', 9),
 ('Sulangan', 9),
 ('Kabangbang', 9),
 ('Tamiao', 9),
 ('Kampingganon', 9),
 ('Bantigue (Pob.)', 9),
 ('Kangkaibe', 9),
 ('Ticad (Pob.)', 9),
 ('Lipayran', 9),
 ('Azucena', 10),
 ('Luyo', 10),
 ('Bagakay', 10),
 ('Maghanoy', 10),
 ('Balao', 10),
 ('Maigang', 10),
 ('Bolocboloc', 10),
 ('Malolos', 10),
 ('Budbud', 10),
 ('Mantalongon', 10),
 ('Bugtong Kawayan', 10),
 ('Mantayupan', 10),
 ('Cabcaban', 10),
 ('Mayana', 10),
 ('Campangga', 10),
 ('Minolos', 10),
 ('Dakit', 10),
 ('Nabunturan', 10),
 ('Giloctog', 10),
 ('Nasipit', 10),
 ('Guibuangan', 10),
 ('Pancil', 10),
 ('Giwanon', 10),
 ('Pangpang', 10),
 ('Gunting', 10),
 ('Paril', 10),
 ('Hilasgasan', 10),
 ('Patupat', 10),
 ('Japitan', 10),
 ('Poblacion', 10),
 ('Cagay', 10),
 ('San Rafael', 10),
 ('Kalubihan', 10),
 ('Santa Ana', 10),
 ('Kangdampas', 10),
 ('Sayaw', 10),
 ('Candugay', 10),
 ('Tal-ot', 10),
 ('Luhod', 10),
 ('Tubod', 10),
 ('Lupo', 10),
 ('Vito', 10),
 ('Cogon (Pob.)', 11),
 ('Lourdes (Pob.)', 11),
 ('Anonang Norte', 11),
 ('Malingin', 11),
 ('Anonang Sur', 11),
 ('Marangog', 11),
 ('Banban', 11),
 ('Nailon', 11),
 ('Binabag', 11),
 ('Odlot', 11),
 ('Bungtod (Pob.)', 11),
 ('Pandan (Pandan Heights)', 11),
 ('Carbon (Pob.)', 11),
 ('Polambato', 11),
 ('Cayang', 11),
 ('Sambag (Pob.)', 11),
 ('Dakit', 11),
 ('San Vicente (Pob.)', 11),
 ('Don Pedro Rodriguez', 11),
 ('Santo Niño', 11),
 ('Gairan', 11),
 ('Santo Rosario (Pob.)', 11),
 ('Guadalupe', 11),
 ('Siocon', 11),
 ('La Paz', 11),
 ('Taytayan', 11),
 ('La Purisima Concepcion (Pob.)', 11),
 ('Sudlonon', 11),
 ('Libertad', 11),
 ('Baclayan', 12),
 ('Upper Becerril', 12),
 ('El Pardo', 12),
 ('Arbor', 12),
 ('Granada', 12),
 ('Lunop', 12),
 ('Lower Becerril', 12),
 ('Nangka', 12),
 ('Poblacion', 12),
 ('South Granada', 12),
 ('San Antonio', 12),
 ('Bagacay', 13),
 ('Don Gregorio Antigua (Taytayan)', 13),
 ('Bili', 13),
 ('Laaw', 13),
 ('Bingay', 13),
 ('Lugo', 13),
 ('Bongdo', 13),
 ('Managase', 13),
 ('Bongdo Gua', 13),
 ('Poblacion', 13),
 ('Bongoyan', 13),
 ('Sagay', 13),
 ('Cadaruhan', 13),
 ('San Jose', 13),
 ('Cajel', 13),
 ('Tabunan', 13),
 ('Campusong', 13),
 ('Tagnucan', 13),
 ('Clavera', 13),
 ('Bolinawan', 14),
 ('Perrelos', 14),
 ('Buenavista', 14),
 ('Valencia', 14),
 ('Calidngan', 14),
 ('Valladolid', 14),
 ('Can-asujan', 14),
 ('Poblacion I', 14),
 ('Guadalupe', 14),
 ('Poblacion II', 14),
 ('Liburon', 14),
 ('Poblacion III', 14),
 ('Napo', 14),
 ('Tuyom', 14),
 ('Ocana', 14),
 ('Baring', 15),
 ('Lanipga', 15),
 ('Cantipay', 15),
 ('Liboron', 15),
 ('Cantumog', 15),
 ('Lower Natimao-an', 15),
 ('Cantukong', 15),
 ('Luyang', 15),
 ('Caurasan', 15),
 ('Poblacion', 15),
 ('Corte', 15),
 ('Puente', 15),
 ('Dawis Norte', 15),
 ('Sac-on', 15),
 ('Dawis Sur', 15),
 ('Triumfo', 15),
 ('Cogon East', 15),
 ('Upper Natimao-an', 15),
 ('Hagnaya', 15),
 ('Cogon West', 15),
 ('Ipil', 15),
 ('Agsuwao', 16),
 ('Catmondaan', 16),
 ('Amancion', 16),
 ('Duyan', 16),
 ('Anapog', 16),
 ('Ginabucan', 16),
 ('Bactas', 16),
 ('Macaas', 16),
 ('Bongyas', 16),
 ('Panalipan', 16),
 ('Basak', 16),
 ('Tabili', 16),
 ('Binongkalan', 16),
 ('Tinabyonan', 16),
 ('Cabungaan', 16),
 ('San Jose Pob. (Catadman)', 16),
 ('Cambangkaya', 16),
 ('Corazon (Pob.)', 16),
 ('Can-ibuang', 16),
 ('Flores (Pob.)', 16),
 ('Adlaon', 17),
 ('Mabini', 17),
 ('Agsungot', 17),
 ('Mabolo', 17),
 ('Apas', 17),
 ('Malubog', 17),
 ('Babag', 17),
 ('Mambaling', 17),
 ('Basak Pardo', 17),
 ('Pahina Central (Pob.)', 17),
 ('Bacayan', 17),
 ('Pahina San Nicolas', 17),
 ('Banilad', 17),
 ('Pamutan', 17),
 ('Basak San Nicolas', 17),
 ('Pardo (Pob.)', 17),
 ('Binaliw', 17),
 ('Pari-an', 17),
 ('Bonbon', 17),
 ('Paril', 17),
 ('Budla-an (Pob.)', 17),
 ('Pasil', 17),
 ('Buhisan', 17),
 ('Pit-os', 17),
 ('Bulacao', 17),
 ('Pulangbato', 17),
 ('Buot-Taup Pardo', 17),
 ('Pung-ol-Sibugay', 17),
 ('Busay (Pob.)', 17),
 ('Punta Princesa', 17),
 ('Calamba', 17),
 ('Quiot Pardo', 17),
 ('Cambinocot', 17),
 ('Sambag I (Pob.)', 17),
 ('Capitol Site (Pob.)', 17),
 ('Sambag II (Pob.)', 17),
 ('Carreta', 17),
 ('San Antonio (Pob.)', 17),
 ('Central (Pob.)', 17),
 ('San Jose', 17),
 ('Cogon Ramos (Pob.)', 17),
 ('San Nicolas Central', 17),
 ('Cogon Pardo', 17),
 ('San Roque (Ciudad)', 17),
 ('Day-as', 17),
 ('Santa Cruz (Pob.)', 17),
 ('Duljo (Pob.)', 17),
 ('Sawang Calero (Pob.)', 17),
 ('Ermita (Pob.)', 17),
 ('Sinsin', 17),
 ('Guadalupe', 17),
 ('Sirao', 17),
 ('Guba', 17),
 ('Suba Pob. (Suba San Nicolas)', 17),
 ('Hippodromo', 17),
 ('Sudlon I', 17),
 ('Inayawan', 17),
 ('Sapangdaku', 17),
 ('Kalubihan (Pob.)', 17),
 ('T. Padilla', 17),
 ('Kalunasan', 17),
 ('Tabunan', 17),
 ('Kamagayan (Pob.)', 17),
 ('Tagbao', 17),
 ('Camputhaw (Pob.)', 17),
 ('Talamban', 17),
 ('Kasambagan', 17),
 ('Taptap', 17),
 ('Kinasang-an Pardo', 17),
 ('Tejero (Villa Gonzalo)', 17),
 ('Labangon', 17),
 ('Tinago', 17),
 ('Lahug (Pob.)', 17),
 ('Tisa', 17),
 ('Lorega (Lorega San Miguel)', 17),
 ('To-ong Pardo', 17),
 ('Lusaran', 17),
 ('Zapatera', 17),
 ('Luz', 17),
 ('Sudlon II', 17),
 ('Bagalnga', 18),
 ('Lupa', 18),
 ('Basak', 18),
 ('Magay', 18),
 ('Buluang', 18),
 ('Mulao', 18),
 ('Cabadiangan', 18),
 ('Panangban', 18),
 ('Cambayog', 18),
 ('Poblacion', 18),
 ('Canamucan', 18),
 ('Tag-ube', 18),
 ('Cogon', 18),
 ('Tamiao', 18),
 ('Dapdap', 18),
 ('Tubigan', 18),
 ('Estaca', 18),
 ('Cabangahan', 19),
 ('Pitogo', 19),
 ('Cansaga', 19),
 ('Poblacion Occidental', 19),
 ('Casili', 19),
 ('Poblacion Oriental', 19),
 ('Danglag', 19),
 ('Polog', 19),
 ('Garing', 19),
 ('Pulpogan', 19),
 ('Jugan', 19),
 ('Sacsac', 19),
 ('Lamac', 19),
 ('Tayud', 19),
 ('Lanipga', 19),
 ('Tilhaong', 19),
 ('Nangka', 19),
 ('Tolotolo', 19),
 ('Panas', 19),
 ('Tugbongan', 19),
 ('Panoypoy', 19),
 ('Alegria', 20),
 ('Gabi', 20),
 ('Bangbang', 20),
 ('Gilutongan', 20),
 ('Buagsong', 20),
 ('Ibabao', 20),
 ('Catarman', 20),
 ('Pilipog', 20),
 ('Cogon', 20),
 ('Poblacion', 20),
 ('Dapitan', 20),
 ('San Miguel', 20),
 ('Day-as', 20),
 ('Aguho', 21),
 ('Malbago', 21),
 ('Bagay', 21),
 ('Malingin', 21),
 ('Bakhawan', 21),
 ('Maya', 21),
 ('Bateria', 21),
 ('Pajo', 21),
 ('Bitoon', 21),
 ('Paypay', 21),
 ('Calape', 21),
 ('Poblacion', 21),
 ('Carnaza', 21),
 ('Talisay', 21),
 ('Dalingding', 21),
 ('Tapilon', 21),
 ('Lanao', 21),
 ('Tinubdan', 21),
 ('Logon', 21),
 ('Tominjao', 21),
 ('Ablayan', 22),
 ('Lumbang', 22),
 ('Babayongan', 22),
 ('Malones', 22),
 ('Balud', 22),
 ('Maloray', 22),
 ('Banhigan', 22),
 ('Mananggal', 22),
 ('Bulak', 22),
 ('Manlapay', 22),
 ('Caliongan', 22),
 ('Mantalongon', 22),
 ('Caleriohan', 22),
 ('Nalhub', 22),
 ('Casay', 22),
 ('Obo', 22),
 ('Catolohan', 22),
 ('Obong', 22),
 ('Cawayan', 22),
 ('Panas', 22),
 ('Consolacion', 22),
 ('Poblacion', 22),
 ('Coro', 22),
 ('Sacsac', 22),
 ('Dugyan', 22),
 ('Tapun', 22),
 ('Dumalan', 22),
 ('Tuba', 22),
 ('Jolomaynon', 22),
 ('Salug', 22),
 ('Lanao', 22),
 ('Tabon', 22),
 ('Langkas', 22),
 ('Baliang', 23),
 ('Manlayag', 23),
 ('Bayabas', 23),
 ('Mantija', 23),
 ('Binaliw', 23),
 ('Masaba', 23),
 ('Cabungahan', 23),
 ('Maslog', 23),
 ('Cagat-Lamac', 23),
 ('Nangka', 23),
 ('Cahumayan', 23),
 ('Oguis', 23),
 ('Cambanay', 23),
 ('Pili', 23),
 ('Cambubho', 23),
 ('Poblacion', 23),
 ('Cogon-Cruz', 23),
 ('Quisol', 23),
 ('Danasan', 23),
 ('Sabang', 23),
 ('Dungga', 23),
 ('Sacsac', 23),
 ('Dunggoan', 23),
 ('Sandayong Norte', 23),
 ('Guinacot', 23),
 ('Sandayong Sur', 23),
 ('Guinsay', 23),
 ('Santa Rosa', 23),
 ('Ibo', 23),
 ('Santican', 23),
 ('Langosig', 23),
 ('Sibacan', 23),
 ('Lawaan', 23),
 ('Suba', 23),
 ('Licos', 23),
 ('Taboc', 23),
 ('Looc', 23),
 ('Taytay', 23),
 ('Magtagobtob', 23),
 ('Togonon', 23),
 ('Malapoc', 23),
 ('Tuburan Sur', 23),
 ('Balaygtiki', 24),
 ('Cotcoton', 24),
 ('Bitoon', 24),
 ('Lamak', 24),
 ('Bulak', 24),
 ('Lawaan', 24),
 ('Bullogan', 24),
 ('Liong', 24),
 ('Doldol', 24),
 ('Manlapay', 24),
 ('Kabalaasnan', 24),
 ('Masa', 24),
 ('Kabatbatan', 24),
 ('Matalao', 24),
 ('Calaboon', 24),
 ('Paculob', 24),
 ('Kambanog', 24),
 ('Panlaan', 24),
 ('Camboang', 24),
 ('Pawa', 24),
 ('Candabong', 24),
 ('Ilaya (Pob.)', 24),
 ('Kang-actol', 24),
 ('Poblacion Looc', 24),
 ('Kanghalo', 24),
 ('Poblacion Sima', 24),
 ('Kanghumaod', 24),
 ('Tangil', 24),
 ('Kanguha', 24),
 ('Tapon', 24),
 ('Kantangkas', 24),
 ('Tubod-Bitoon', 24),
 ('Kanyuko', 24),
 ('Tubod-Dugoan', 24),
 ('Cogon', 24),
 ('Poblacion Central', 24),
 ('Kolabtingon', 24),
 ('Anao', 25),
 ('Looc', 25),
 ('Cagsing', 25),
 ('Malatbo', 25),
 ('Calabawan', 25),
 ('Mangaco', 25),
 ('Cambagte', 25),
 ('Palanas', 25),
 ('Campisong', 25),
 ('Poblacion', 25),
 ('Canorong', 25),
 ('Salamanca', 25),
 ('Guiwanon', 25),
 ('San Roque', 25),
 ('Agus', 26),
 ('Maribago', 26),
 ('Babag', 26),
 ('Marigondon', 26),
 ('Bankal', 26),
 ('Pajac', 26),
 ('Baring', 26),
 ('Pajo', 26),
 ('Basak', 26),
 ('Pangan-an', 26),
 ('Buaya', 26),
 ('Poblacion', 26),
 ('Calawisan', 26),
 ('Punta Engaño', 26),
 ('Canjulao', 26),
 ('Pusok', 26),
 ('Caw-oy', 26),
 ('Sabang', 26),
 ('Cawhagan', 26),
 ('Santa Rosa', 26),
 ('Caubian', 26),
 ('Subabasbas', 26),
 ('Gun-ob', 26),
 ('Talima', 26),
 ('Ibo', 26),
 ('Tingo', 26),
 ('Looc', 26),
 ('Tungasan', 26),
 ('Mactan', 26),
 ('San Vicente', 26),
 ('Cabadiangan', 27),
 ('Poblacion', 27),
 ('Calero', 27),
 ('San Roque', 27),
 ('Catarman', 27),
 ('San Vicente', 27),
 ('Cotcot', 27),
 ('Santa Cruz', 27),
 ('Jubay', 27),
 ('Tabla', 27),
 ('Lataban', 27),
 ('Tayud', 27),
 ('Mulao', 27),
 ('Yati', 27),
 ('Bunakan', 28),
 ('Pili', 28),
 ('Kangwayan', 28),
 ('Poblacion', 28),
 ('Kaongkod', 28),
 ('San Agustin', 28),
 ('Kodia', 28),
 ('Tabagak', 28),
 ('Maalat', 28),
 ('Talangnan', 28),
 ('Malbago', 28),
 ('Tarong', 28),
 ('Mancilang', 28),
 ('Tugas', 28),
 ('Armeña (Cansilongan)', 29),
 ('Mindanao (Pajo)', 29),
 ('Tolosa (Calatagan)', 29),
 ('Montañeza (Inamlang)', 29),
 ('Cerdeña (Ansan)', 29),
 ('Salmeron (Bulak)', 29),
 ('Labrador (Bulod)', 29),
 ('Santo Niño', 29),
 ('Looc', 29),
 ('Sorsogon (Balimaya)', 29),
 ('Lombo', 29),
 ('Barangay I (Pob.)', 29),
 ('Mahanlud', 29),
 ('Barangay II (Pob.)', 29),
 ('Alang-alang', 30),
 ('Labogon', 30),
 ('Bakilid', 30),
 ('Looc', 30),
 ('Banilad', 30),
 ('Maguikay', 30),
 ('Basak', 30),
 ('Mantuyong', 30),
 ('Cabancalan', 30),
 ('Opao', 30),
 ('Cambaro', 30),
 ('Pakna-an', 30),
 ('Canduman', 30),
 ('Pagsabungan', 30),
 ('Casili', 30),
 ('Subangdaku', 30),
 ('Casuntingan', 30),
 ('Tabok', 30),
 ('Centro (Pob.)', 30),
 ('Tawason', 30),
 ('Cubacub', 30),
 ('Tingub', 30),
 ('Guizo', 30),
 ('Tipolo', 30),
 ('Ibabao-Estancia', 30),
 ('Umapad', 30),
 ('Jagobiao', 30),
 ('Antipolo', 31),
 ('Lamintak Norte', 31),
 ('Curva', 31),
 ('Luy-a', 31),
 ('Daanlungsod', 31),
 ('Panugnawan', 31),
 ('Dalingding Sur', 31),
 ('Poblacion', 31),
 ('Dayhagon', 31),
 ('Tindog', 31),
 ('Gibitngil', 31),
 ('Don Virgilio Gonzales', 31),
 ('Canhabagat', 31),
 ('Lamintak Sur', 31),
 ('Caputatan Norte', 31),
 ('Maharuhay', 31),
 ('Caputatan Sur', 31),
 ('Mahawak', 31),
 ('Kawit', 31),
 ('Cadulawan', 32),
 ('Poblacion Ward II', 32),
 ('Calajo-an', 32),
 ('Poblacion Ward III', 32),
 ('Camp 7', 32),
 ('Poblacion Ward IV', 32),
 ('Camp 8', 32),
 ('Tubod', 32),
 ('Cuanos', 32),
 ('Tulay', 32),
 ('Guindaruhan', 32),
 ('Tunghaan', 32),
 ('Linao', 32),
 ('Tungkop', 32),
 ('Manduang', 32),
 ('Vito', 32),
 ('Pakigne', 32),
 ('Tungkil', 32),
 ('Poblacion Ward I', 32),
 ('Agbalanga', 33),
 ('Lanao', 33),
 ('Bala', 33),
 ('Poblacion East', 33),
 ('Balabagon', 33),
 ('Poblacion West', 33),
 ('Basdiot', 33),
 ('Saavedra', 33),
 ('Batadbatad', 33),
 ('Tomonoy', 33),
 ('Bugho', 33),
 ('Tuble', 33),
 ('Buguil', 33),
 ('Tunga', 33),
 ('Busay', 33),
 ('Alfaco', 34),
 ('Lutac', 34),
 ('Bairan', 34),
 ('Mainit', 34),
 ('Balirong', 34),
 ('Mayana', 34),
 ('Cabungahan', 34),
 ('Naalad', 34),
 ('Cantao-an', 34),
 ('North Poblacion', 34),
 ('Central Poblacion', 34),
 ('Pangdan', 34),
 ('Cogon', 34),
 ('Patag', 34),
 ('Colon', 34),
 ('South Poblacion', 34),
 ('East Poblacion', 34),
 ('Tagjaguimit', 34),
 ('Inoburan', 34),
 ('Tangke', 34),
 ('Inayagan', 34),
 ('Tinaan', 34),
 ('Jaguimit', 34),
 ('Tuyan', 34),
 ('Lanas', 34),
 ('Uling', 34),
 ('Langtad', 34),
 ('West Poblacion', 34),
 ('Alo', 35),
 ('Lagunde', 35),
 ('Bangcogon', 35),
 ('Looc', 35),
 ('Bonbon', 35),
 ('Luka', 35),
 ('Calumpang', 35),
 ('Mainit', 35),
 ('Canangca-an', 35),
 ('Manlum', 35),
 ('Cañang', 35),
 ('Nueva Caceres', 35),
 ('Can-ukban', 35),
 ('Poblacion', 35),
 ('Cansalo-ay', 35),
 ('Pungtod', 35),
 ('Daanlungsod', 35),
 ('Tan-awan', 35),
 ('Gawi', 35),
 ('Tumalog', 35),
 ('Hagdan', 35),
 ('Biasong', 36),
 ('Montserrat', 36),
 ('Cawit', 36),
 ('San Isidro', 36),
 ('Dapdap', 36),
 ('San Juan', 36),
 ('Esperanza', 36),
 ('Upper Poblacion', 36),
 ('Lanao', 36),
 ('Villahermosa', 36),
 ('Lower Poblacion', 36),
 ('Imelda', 36),
 ('Moabog', 36),
 ('Anislag', 37),
 ('Opao', 37),
 ('Anopog', 37),
 ('Pandacan', 37),
 ('Binabag', 37),
 ('Poblacion', 37),
 ('Buhingtubig', 37),
 ('Punod', 37),
 ('Busay', 37),
 ('Rizal', 37),
 ('Butong', 37),
 ('Sacsac', 37),
 ('Cabiangon', 37),
 ('Sambagon', 37),
 ('Camugao', 37),
 ('Sibago', 37),
 ('Duangan', 37),
 ('Tajao', 37),
 ('Guimbawian', 37),
 ('Tangub', 37),
 ('Lamac', 37),
 ('Tanibag', 37),
 ('Lut-od', 37),
 ('Tupas', 37),
 ('Mangoto', 37),
 ('Tutay', 37),
 ('Adela', 38),
 ('Mercedes', 38),
 ('Altavista', 38),
 ('Pagsa', 38),
 ('Cagcagan', 38),
 ('Paz', 38),
 ('Cansabusab', 38),
 ('Rizal', 38),
 ('Daan Paz', 38),
 ('San Jose', 38),
 ('Eastern Poblacion', 38),
 ('Santa Rita', 38),
 ('Esperanza', 38),
 ('Teguis', 38),
 ('Libertad', 38),
 ('Western Poblacion', 38),
 ('Mabini', 38),
 ('Butong', 39),
 ('Libo-o', 39),
 ('Can-abuhon', 39),
 ('Malalay', 39),
 ('Canduling', 39),
 ('Palanas', 39),
 ('Cansalonoy', 39),
 ('Poblacion', 39),
 ('Cansayahon', 39),
 ('Santa Cruz', 39),
 ('Ilaya', 39),
 ('Tupas', 39),
 ('Langin', 39),
 ('Vive', 39),
 ('Basak', 40),
 ('Jumangpas', 40),
 ('Bonbon', 40),
 ('Camburoy', 40),
 ('Bulangsuran', 40),
 ('Poblacion', 40),
 ('Calatagan', 40),
 ('San Sebastian', 40),
 ('Cambigong', 40),
 ('Suba', 40),
 ('Canorong', 40),
 ('Tangbo', 40),
 ('Colase', 40),
 ('Monteverde', 40),
 ('Dalahikan', 40),
 ('Balud', 41),
 ('Pitalo', 41),
 ('Balungag', 41),
 ('San Isidro', 41),
 ('Basak', 41),
 ('Sangat', 41),
 ('Bugho', 41),
 ('Poblacion South', 41),
 ('Cabatbatan', 41),
 ('Tabionan', 41),
 ('Greenhills', 41),
 ('Tananas', 41),
 ('Lantawan', 41),
 ('Tinubdan', 41),
 ('Liburon', 41),
 ('Tonggo', 41),
 ('Magsico', 41),
 ('Tubod', 41),
 ('Poblacion North', 41),
 ('Ilaya', 41),
 ('Panadtaran', 41),
 ('Montealegre', 42),
 ('Santa Cruz', 42),
 ('Cabunga-an', 42),
 ('Santiago', 42),
 ('Campo', 42),
 ('Sonog', 42),
 ('Consuelo', 42),
 ('Southern Poblacion', 42),
 ('Esperanza', 42),
 ('Unidos', 42),
 ('Himensulan', 42),
 ('Union', 42),
 ('Northern Poblacion', 42),
 ('Western Poblacion', 42),
 ('San Isidro', 42),
 ('Anapog', 43),
 ('Lawis', 43),
 ('Argawanon', 43),
 ('Libaong', 43),
 ('Bagtic', 43),
 ('Looc', 43),
 ('Bancasan', 43),
 ('Luyang', 43),
 ('Batad', 43),
 ('Mano', 43),
 ('Busogon', 43),
 ('Poblacion', 43),
 ('Calambua', 43),
 ('Punta', 43),
 ('Canagahan', 43),
 ('Sab-a', 43),
 ('Dapdap', 43),
 ('San Miguel', 43),
 ('Gawaygaway', 43),
 ('Tacup', 43),
 ('Hagnaya', 43),
 ('Tambongon', 43),
 ('Kayam', 43),
 ('To-ong', 43),
 ('Kinawahan', 43),
 ('Victoria', 43),
 ('Lambusan', 43),
 ('Hagdan', 44),
 ('Okoy', 44),
 ('Hilantagaan', 44),
 ('Poblacion', 44),
 ('Kinatarkan', 44),
 ('Balidbid', 44),
 ('Langub', 44),
 ('Pooc', 44),
 ('Maricaban', 44),
 ('Talisay', 44),
 ('Bunlan', 45),
 ('Looc', 45),
 ('Cabutongan', 45),
 ('Pasil', 45),
 ('Candamiang', 45),
 ('Poblacion', 45),
 ('Liloan', 45),
 ('Talisay', 45),
 ('Lip-tong', 45),
 ('Canlumacad', 45),
 ('Abugon', 46),
 ('Lamacan', 46),
 ('Bae', 46),
 ('Libo', 46),
 ('Bagacay', 46),
 ('Lindogon', 46),
 ('Bahay', 46),
 ('Magcagong', 46),
 ('Banlot', 46),
 ('Manatad', 46),
 ('Basak', 46),
 ('Mangyan', 46),
 ('Bato', 46),
 ('Papan', 46),
 ('Cagay', 46),
 ('Poblacion', 46),
 ('Can-aga', 46),
 ('Sabang', 46),
 ('Candaguit', 46),
 ('Sayao', 46),
 ('Cantolaroy', 46),
 ('Simala', 46),
 ('Dugoan', 46),
 ('Tubod', 46),
 ('Guimbangco-an', 46),
 ('Ampongol', 47),
 ('Ibabao', 47),
 ('Bagakay', 47),
 ('Liki', 47),
 ('Bagatayam', 47),
 ('Lubo', 47),
 ('Bawo', 47),
 ('Mohon', 47),
 ('Cabalawan', 47),
 ('Nahus-an', 47),
 ('Cabangahan', 47),
 ('Poblacion', 47),
 ('Calumboyan', 47),
 ('Tabunok', 47),
 ('Dakit', 47),
 ('Takay', 47),
 ('Damolog', 47),
 ('Pansoy', 47),
 ('Alang-alang', 48),
 ('Manlagtang', 48),
 ('Caduawan', 48),
 ('Maslog', 48),
 ('Kal-anan', 48),
 ('Muabog', 48),
 ('Camoboan', 48),
 ('Pio', 48),
 ('Canaocanao', 48),
 ('Poblacion', 48),
 ('Combado', 48),
 ('Salag', 48),
 ('Daantabogon', 48),
 ('Sambag', 48),
 ('Ilihan', 48),
 ('San Isidro', 48),
 ('Labangon', 48),
 ('San Vicente', 48),
 ('Libjo', 48),
 ('Somosa', 48),
 ('Loong', 48),
 ('Taba-ao', 48),
 ('Mabuli', 48),
 ('Tapul', 48),
 ('Managase', 48),
 ('Bongon', 49),
 ('Maravilla', 49),
 ('Kanlim-ao', 49),
 ('Olivo', 49),
 ('Kanluhangon', 49),
 ('Poblacion', 49),
 ('Kantubaon', 49),
 ('Tabunok', 49),
 ('Dalid', 49),
 ('Tigbawan', 49),
 ('Mabunao', 49),
 ('Villahermosa', 49),
 ('Bulacao', 50),
 ('Poblacion', 50),
 ('Cadulawan', 50),
 ('Pooc', 50),
 ('Cansojong', 50),
 ('San Isidro', 50),
 ('Dumlog', 50),
 ('San Roque', 50),
 ('Jaclupan', 50),
 ('Tabunoc', 50),
 ('Lagtang', 50),
 ('Tangke', 50),
 ('Lawaan I', 50),
 ('Tapul', 50),
 ('Linao', 50),
 ('Biasong', 50),
 ('Maghaway', 50),
 ('Camp IV', 50),
 ('Manipis', 50),
 ('Lawaan II', 50),
 ('Mohon', 50),
 ('Lawaan III', 50),
 ('Awihao', 51),
 ('Media Once', 51),
 ('Bagakay', 51),
 ('Pangamihan', 51),
 ('Bato', 51),
 ('Poblacion', 51),
 ('Biga', 51),
 ('Poog', 51),
 ('Bulongan', 51),
 ('Putingbato', 51),
 ('Bunga', 51),
 ('Sagay', 51),
 ('Cabitoonan', 51),
 ('Sam-ang', 51),
 ('Calongcalong', 51),
 ('Sangi', 51),
 ('Cambang-ug', 51),
 ('Santo Niño (Mainggit)', 51),
 ('Camp 8', 51),
 ('Subayon', 51),
 ('Canlumampao', 51),
 ('Talavera', 51),
 ('Cantabaco', 51),
 ('Tungkay', 51),
 ('Capitan Claudio', 51),
 ('Tubod', 51),
 ('Carmen', 51),
 ('Sangi', 51),
 ('Daanglungsod', 51),
 ('Santo Niño (Mainggit)', 51),
 ('Don Andres Soriano (Lutopan)', 51),
 ('Subayon', 51),
 ('Dumlog', 51),
 ('Talavera', 51),
 ('Ibo', 51),
 ('Tungkay', 51),
 ('Ilihan', 51),
 ('Tubod', 51),
 ('Alegria', 52),
 ('Libo', 52),
 ('Amatugan', 52),
 ('Lusong', 52),
 ('Antipolo', 52),
 ('Macupa', 52),
 ('Apalan', 52),
 ('Mag-alwa', 52),
 ('Bagasawe', 52),
 ('Mag-antoy', 52),
 ('Bakyawan', 52),
 ('Mag-atubang', 52),
 ('Bangkito', 52),
 ('Maghan-ay', 52),
 ('Bulwang', 52),
 ('Mangga', 52),
 ('Kabangkalan', 52),
 ('Marmol', 52),
 ('Kalangahan', 52),
 ('Molobolo', 52),
 ('Kamansi', 52),
 ('Montealegre', 52),
 ('Kan-an', 52),
 ('Putat', 52),
 ('Kanlunsing', 52),
 ('San Juan', 52),
 ('Kansi', 52),
 ('Sandayong', 52),
 ('Caridad', 52),
 ('Santo Niño', 52),
 ('Carmelo', 52),
 ('Siotes', 52),
 ('Cogon', 52),
 ('Sumon', 52),
 ('Colonia', 52),
 ('Tominjao', 52),
 ('Daan Lungsod', 52),
 ('Tomugpa', 52),
 ('Fortaliza', 52),
 ('Barangay I (Pob.)', 52),
 ('Ga-ang', 52),
 ('Barangay II (Pob.)', 52),
 ('Gimama-a', 52),
 ('Barangay III (Pob.)', 52),
 ('Jagbuaya', 52),
 ('Barangay IV (Pob.)', 52),
 ('Kabkaban', 52),
 ('Barangay V (Pob.)', 52),
 ('Kagba-o', 52),
 ('Barangay VI (Pob.)', 52),
 ('Kampoot', 52),
 ('Barangay VII (Pob.)', 52),
 ('Kaorasan', 52),
 ('Barangay VIII (Pob.)', 52),
 ('Buenavista', 53),
 ('Puertobello', 53),
 ('Calmante', 53),
 ('Santander', 53),
 ('Daan Secante', 53),
 ('Secante Bag-o', 53),
 ('General', 53),
 ('Southern Poblacion', 53),
 ('McArthur', 53),
 ('Villahermosa', 53),
 ('Northern Poblacion', 53);

    """

    with Session(engine) as session:
        # Check if LGUs already exist
        lgu_count = session.execute(text("SELECT COUNT(*) FROM lgu_records")).scalar()

        if lgu_count == 0:
            print("✅ lgu_records table is empty. Inserting data...")
            session.execute(text(lgu_sql))
            print("✅ LGUs inserted.")

            # Now also insert into barangay_records
            session.execute(text(barangay_sql))
            print("✅ Barangays inserted.")

            session.commit()
            print("✅ All inserts committed successfully.")
        else:
            print(f"ℹ️ lgu_records already has {lgu_count} entries. Skipping inserts.")
